stages:
  - Cluster Setup
  - App Deploy 

image: docker:stable
variables:
  KUBECTL: v1.17.0
  KIND: v0.7.0
services:
  - docker:dind

SetupKinD:
  stage: Cluster Setup
  tags:
    - k3s
  script:
    - path=$(pwd)
    - apk add -U wget
    - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - kind create cluster --config=./gitlab/kind-config.yaml
    - sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' "$HOME/.kube/config"
    - kubectl get nodes -o wide
    - kubectl get pods --all-namespaces -o wide
    - kubectl get services --all-namespaces -o wide
    - sleep 30
    - kubectl cluster-info --context kind-kind
    - kubectl get nodes

DeployApp:
  image: uditgaurav/kind:ci
  stage: App Deploy
  tags:
    - k3s  
  script: 
    - ls -a
    - k3s --version
    - kubectl get nodes
  dependencies: 
    - SetupKinD    
