stages:
  - Cluster Setup
  - App Deploy 

image: docker:stable
variables:
  KUBECTL: v1.17.0
  KIND: v0.7.0
services:
  - docker:dind

.before_script_template:
  before_script:

    - export GOPATH=$HOME/go
    - export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
    - mkdir -p $HOME/go/src/github.com/uditgaurav1/kind
    - rsync -az --delete ${CI_PROJECT_DIR}/ ${GOPATH}/src/github.com/uditgaurav1/kind/ #CI_PROJECT_DIR is full path where project is cloned
    - cd $HOME/go/src/github.com/uditgaurav1/kind

SetupKinD:
  stage: Cluster Setup
  extends: .before_script_template
  script:
    - path=$(pwd)
    - apk add -U wget
    - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - kind create cluster --config=./gitlab/kind-config.yaml
    - sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' "$HOME/.kube/config"
    - kubectl get nodes -o wide
    - kubectl get pods --all-namespaces -o wide
    - kubectl get services --all-namespaces -o wide
    - sleep 30
    - kubectl cluster-info --context kind-kind
    - kubectl get nodes
    - mkdir $path/.kube
    - cat ~/.kube/config > $path/.kube/config

  artifacts:
    when: always
    paths:
      - .kube/
      - /usr/local/bin/

DeployApp:
  image: uditgaurav/kind:ci
  extends: .before_script_template
  stage: App Deploy
  script: 
    - ls -a
    - kind --version
    - kubectl get nodes
  dependencies: 
    - SetupKinD    
